server:
  port: 9999
spring:
  profiles:
    active: dev
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      client-type: lettuce
langchain4j:
  open-ai:
    streaming-chat-model:
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      api-key: ${BL_API_KEY}
      model-name: qwen-plus
      log-requests: true
      log-responses: true